language: ruby
rvm:
  - "1.9.3"
  - "2.0.0"
script:
  - RAILS_ENV=test bundle exec rake db:setup --trace
  - bundle exec rake db:test:prepare
  - bundle exec rake
before_script:
  - psql -c 'create database katikia_test;' -U postgres
services:
  - redis-server
  - elasticsearch
