development: &defaults
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: postgres
  password:

development:
  database: katikia_development
  <<: *defaults

test:
  database: katikia_test
  <<: *defaults

production:
  database: katikia_production
  <<: *defaults
